MAP_SIZE = 64
MAP_AREA = MAP_SIZE * MAP_SIZE
MAP_HEIGHT = MAP_SIZE
MAP_WIDTH = MAP_SIZE

AMBUSH_TILE = 106
AREA_TILE = 107         # first of NUMAREAS floor tiles

START_AMMO = 8
WP_KNIFE = 0
WP_PISTOL = 1
WP_MACHINEGUN = 2
WP_CHAINGUN = 3
